services:
  db:
    image: "postgres:16"
    container_name: zoula_air_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user_zoula
      POSTGRES_PASSWORD: password_zoula
      POSTGRES_DB: zoula_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_auth
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: unless-stopped
    volumes:
      - ././redis-data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
